// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated by transport_security_state_static_generate.go

#ifndef NET_BASE_TRANSPORT_SECURITY_STATE_STATIC_H_
#define NET_BASE_TRANSPORT_SECURITY_STATE_STATIC_H_

// These are TACK key fingerprints and their min_generation values.

static const net::PreloadTackKey kPreloadedTackKeys[] = {
  {"6i7l7.gw7zx.kuza6.skvzy.6alwa", 3},
  {"j6det.kfbj5.oweph.mdyxi.wvbch", 0},
  {"k2wgv.l24nx.yiqyc.zjir5.md474", 255},
};

// These are SubjectPublicKeyInfo hashes for public key pinning. The
// hashes are SHA1 digests.

static const char kSPKIHash_TestSPKI[] =
    "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00";

static const char kSPKIHash_VeriSignClass3[] =
    "\xe2\x7f\x7b\xd8\x77\xd5\xdf\x9e\x0a\x3f\x9e\xb4\xcb\x0e\x2e\xa9\xef\xdb\x69\x77";

static const char kSPKIHash_VeriSignClass3_G3[] =
    "\x22\xf1\x9e\x2e\xc6\xea\xcc\xfc\x5d\x23\x46\xf4\xc2\xe8\xf6\xc5\x54\xdd\x5e\x07";

static const char kSPKIHash_Google1024[] =
    "\x40\xc5\x40\x1d\x6f\x8c\xba\xf0\x8b\x00\xed\xef\xb1\xee\x87\xd0\x05\xb3\xb9\xcd";

static const char kSPKIHash_Google2048[] =
    "\x01\xb9\x21\xc5\x8d\x0b\xdf\x8d\xe0\x29\xff\x9c\x92\x2e\xcd\x55\x6a\x7e\xa3\x39";

static const char kSPKIHash_EquifaxSecureCA[] =
    "\x48\xe6\x68\xf9\x2b\xd2\xb2\x95\xd7\x47\xd8\x23\x20\x10\x4f\x33\x98\x90\x9f\xd4";

static const char kSPKIHash_Aetna[] =
    "\x92\x52\xaa\x14\xde\xbf\x80\xae\x30\xaa\xd9\x4e\x60\x38\x70\x24\xa5\x43\x2f\x1a";

static const char kSPKIHash_GeoTrustGlobal[] =
    "\xc0\x7a\x98\x68\x8d\x89\xfb\xab\x05\x64\x0c\x11\x7d\xaa\x7d\x65\xb8\xca\xcc\x4e";

static const char kSPKIHash_GeoTrustPrimary[] =
    "\xb0\x19\x89\xe7\xef\xfb\x4a\xaf\xcb\x14\x8f\x58\x46\x39\x76\x22\x41\x50\xe1\xba";

static const char kSPKIHash_Intel[] =
    "\x0e\xc6\x2a\xf7\x59\xb2\x08\x10\x90\x25\x6f\xc3\xdd\xfd\x8a\x66\x31\x30\x2b\xc5";

static const char kSPKIHash_TCTrustCenter[] =
    "\x83\x3b\x84\x10\x00\x7f\x6e\x4a\x9d\x41\x2d\xc4\x22\x39\x36\x6f\x2e\xe5\x5b\xe9";

static const char kSPKIHash_Vodafone[] =
    "\x0d\x7f\xe1\x5c\x55\x14\x36\x68\x99\xfc\x40\xd6\x22\x08\xef\x22\xeb\xd1\x15\x1c";

static const char kSPKIHash_RapidSSL[] =
    "\xa3\x93\x99\xc4\x04\xc3\xb2\x09\xb0\x81\xc2\x1f\x21\x62\x27\x78\xc2\x74\x8e\x4c";

static const char kSPKIHash_DigiCertEVRoot[] =
    "\x83\x31\x7e\x62\x85\x42\x53\xd6\xd7\x78\x31\x90\xec\x91\x90\x56\xe9\x91\xb9\xe3";

static const char kSPKIHash_Tor1[] =
    "\x8e\xe3\x71\x49\x3b\xfd\x50\x03\x66\xa4\x2f\x64\x17\x91\x8a\xa6\x65\x8d\xc7\x76";

static const char kSPKIHash_Tor2[] =
    "\x96\x26\xb8\xde\x53\xe8\x97\x34\x8f\x54\x8a\xb7\xe0\x3c\x39\xee\xe6\x1c\x2c\x3f";

static const char kSPKIHash_Tor3[] =
    "\xaf\x31\x32\x40\x82\x8e\x87\xbe\xe3\xf3\xb9\xf9\x6e\x35\x94\x36\x0b\x97\x17\xc6";

static const char kSPKIHash_VeriSignClass1[] =
    "\x23\x43\xd1\x48\xa2\x55\x89\x9b\x94\x7d\x46\x1a\x79\x7e\xc0\x4c\xfe\xd1\x70\xb7";

static const char kSPKIHash_VeriSignClass3_G4[] =
    "\xed\x66\x31\x35\xd3\x1b\xd4\xec\xa6\x14\xc4\x29\xe3\x19\x06\x9f\x94\xc1\x26\x50";

static const char kSPKIHash_VeriSignClass4_G3[] =
    "\x3c\x03\x43\x68\x68\x95\x1c\xf3\x69\x2a\xb8\xb4\x26\xda\xba\x8f\xe9\x22\xe5\xbd";

static const char kSPKIHash_VeriSignClass1_G3[] =
    "\x55\x19\xb2\x78\xac\xb2\x81\xd7\xed\xa7\xab\xc1\x83\x99\xc3\xbb\x69\x04\x24\xb5";

static const char kSPKIHash_VeriSignClass2_G3[] =
    "\x5a\xbe\xc5\x75\xdc\xae\xf3\xb0\x8e\x27\x19\x43\xfc\x7f\x25\x0c\x3d\xf6\x61\xe3";

static const char kSPKIHash_VeriSignClass3_G2[] =
    "\x1a\x21\xb4\x95\x2b\x62\x93\xce\x18\xb3\x65\xec\x9c\x0e\x93\x4c\xb3\x81\xe6\xd4";

static const char kSPKIHash_VeriSignClass2_G2[] =
    "\x12\x37\xba\x45\x17\xee\xad\x29\x26\xfd\xc1\xcd\xfe\xbe\xed\xf2\xde\xd9\x14\x5c";

static const char kSPKIHash_VeriSignClass3_G5[] =
    "\xb1\x81\x08\x1a\x19\xa4\xc0\x94\x1f\xfa\xe8\x95\x28\xc1\x24\xc9\x9b\x34\xac\xc7";

static const char kSPKIHash_VeriSignUniversal[] =
    "\xbb\xc2\x3e\x29\x0b\xb3\x28\x77\x1d\xad\x3e\xa2\x4d\xbd\xf4\x23\xbd\x06\xb0\x3d";

static const char kSPKIHash_Twitter1[] =
    "\x56\xfe\xf3\xc2\x14\x7d\x4e\xd3\x88\x37\xfd\xbd\x30\x52\x38\x72\x01\xe5\x77\x8d";

static const char kSPKIHash_GeoTrustGlobal2[] =
    "\x71\x38\x36\xf2\x02\x31\x53\x47\x2b\x6e\xba\x65\x46\xa9\x10\x15\x58\x20\x05\x09";

static const char kSPKIHash_GeoTrustUniversal[] =
    "\x87\xe8\x5b\x63\x53\xc6\x23\xa3\x12\x8c\xb0\xff\xbb\xf5\x51\xfe\x59\x80\x0e\x22";

static const char kSPKIHash_GeoTrustUniversal2[] =
    "\x5e\x4f\x53\x86\x85\xdd\x4f\x9e\xca\x5f\xdc\x0d\x45\x6f\x7d\x51\xb1\xdc\x9b\x7b";

static const char kSPKIHash_GeoTrustPrimary_G2[] =
    "\xbd\xbe\xa7\x1b\xab\x71\x57\xf9\xe4\x75\xd9\x54\xd2\xb7\x27\x80\x1a\x82\x26\x82";

static const char kSPKIHash_GeoTrustPrimary_G3[] =
    "\x9c\xa9\x8d\x00\xaf\x74\x0d\xdd\x81\x80\xd2\x13\x45\xa5\x8b\x8f\x2e\x94\x38\xd6";

static const char kSPKIHash_Entrust_2048[] =
    "\x55\xe4\x81\xd1\x11\x80\xbe\xd8\x89\xb9\x08\xa3\x31\xf9\xa1\x24\x09\x16\xb9\x70";

static const char kSPKIHash_Entrust_EV[] =
    "\xba\x42\xb0\x81\x88\x53\x88\x1d\x86\x63\xbd\x4c\xc0\x5e\x08\xfe\xea\x6e\xbb\x77";

static const char kSPKIHash_Entrust_G2[] =
    "\xab\x30\xd3\xaf\x4b\xd8\xf1\x6b\x58\x69\xee\x45\x69\x29\xda\x84\xb8\x73\x94\x88";

static const char kSPKIHash_Entrust_SSL[] =
    "\xf0\x17\x62\x13\x55\x3d\xb3\xff\x0a\x00\x6b\xfb\x50\x84\x97\xf3\xed\x62\xd0\x1a";

static const char kSPKIHash_AAACertificateServices[] =
    "\xc4\x30\x28\xc5\xd3\xe3\x08\x0c\x10\x44\x8b\x2c\x77\xba\x24\x53\x97\x60\xbb\xf9";

static const char kSPKIHash_AddTrustClass1CARoot[] =
    "\x8b\xdb\xd7\xcc\xa0\x68\x53\x42\x16\xf4\xc1\x2b\x25\x44\xfc\x02\x9c\xa5\x8b\x47";

static const char kSPKIHash_AddTrustExternalCARoot[] =
    "\x4f\x9c\x7d\x21\x79\x9c\xad\x0e\xd8\xb9\x0c\x57\x9f\x1a\x02\x99\xe7\x90\xf3\x87";

static const char kSPKIHash_AddTrustPublicCARoot[] =
    "\xa8\x57\x65\xd6\xe8\x32\xc8\xc5\x19\x63\x73\x5a\x9a\x17\x74\x3a\x81\xdf\xee\x2e";

static const char kSPKIHash_AddTrustQualifiedCARoot[] =
    "\xbc\xe4\xb7\x23\x12\x55\x98\xe5\x63\x41\x19\x1c\x50\xe4\xb6\x47\xc2\x76\x05\xd7";

static const char kSPKIHash_COMODOCertificationAuthority[] =
    "\x11\xe4\x91\xd1\xc9\xe4\xc0\xeb\x9a\xce\xcf\x73\x54\x5d\xe1\xf1\xa8\x30\x3e\xc3";

static const char kSPKIHash_SecureCertificateServices[] =
    "\x3c\xb4\x1a\x84\x2e\xf5\x5c\xf2\x1a\x3d\xa5\x4a\xc8\xd1\xbe\x39\x08\x76\x37\xbc";

static const char kSPKIHash_TrustedCertificateServices[] =
    "\xfe\x72\xc8\xeb\xbf\x0c\x2f\xbb\x0e\x26\x13\x93\x93\x3c\x2c\xa9\x8d\xdc\x24\x94";

static const char kSPKIHash_UTNDATACorpSGC[] =
    "\x53\x32\xd1\xb3\xcf\x7f\xfa\xe0\xf1\xa0\x5d\x85\x4e\x92\xd2\x9e\x45\x1d\xb4\x4f";

static const char kSPKIHash_UTNUSERFirstClientAuthenticationandEmail[] =
    "\x89\x82\x67\x7d\xc4\x9d\x26\x70\x00\x4b\xb4\x50\x48\x7c\xde\x3d\xae\x04\x6e\x7d";

static const char kSPKIHash_UTNUSERFirstHardware[] =
    "\xa1\x72\x5f\x26\x1b\x28\x98\x43\x95\x5d\x07\x37\xd5\x85\x96\x9d\x4b\xd2\xc3\x45";

static const char kSPKIHash_UTNUSERFirstObject[] =
    "\xda\xed\x64\x74\x14\x9c\x14\x3c\xab\xdd\x99\xa9\xbd\x5b\x28\x4d\x8b\x3c\xc9\xd8";

static const char kSPKIHash_GTECyberTrustGlobalRoot[] =
    "\x59\x79\x12\xde\x61\x75\xd6\x6f\xc4\x23\xb7\x77\x13\x74\xc7\x96\xde\x6f\x88\x72";

static const char kSPKIHash_Tor2web[] =
    "\x19\xe5\xb5\x87\x1b\xd4\x83\x2e\xc8\xf5\x94\x97\xfe\xc6\x5e\xfb\x48\xe3\x33\xb1";

static const char kSPKIHash_AlphaSSL_G2[] =
    "\xe5\x24\xe9\x8e\x31\x7d\xc8\xfc\xad\x90\x53\x7c\x91\xe7\x0d\xa4\x70\x93\x90\x5f";

// The following is static data describing the hosts that are hardcoded with
// certificate pins or HSTS information.

// kNoRejectedPublicKeys is a placeholder for when no public keys are rejected.
static const char* const kNoRejectedPublicKeys[] = {
  NULL,
};

static const char* const kTestAcceptableCerts[] = {
  kSPKIHash_TestSPKI,
  NULL,
};
#define kTestPins \
  kTestAcceptableCerts, \
  kNoRejectedPublicKeys

static const char* const kGoogleAcceptableCerts[] = {
  kSPKIHash_VeriSignClass3,
  kSPKIHash_VeriSignClass3_G3,
  kSPKIHash_Google1024,
  kSPKIHash_Google2048,
  kSPKIHash_EquifaxSecureCA,
  NULL,
};
static const char* const kGoogleRejectedCerts[] = {
  kSPKIHash_Aetna,
  kSPKIHash_Intel,
  kSPKIHash_TCTrustCenter,
  kSPKIHash_Vodafone,
  NULL,
};
#define kGooglePins \
  kGoogleAcceptableCerts, \
  kGoogleRejectedCerts

static const char* const kTorAcceptableCerts[] = {
  kSPKIHash_RapidSSL,
  kSPKIHash_DigiCertEVRoot,
  kSPKIHash_Tor1,
  kSPKIHash_Tor2,
  kSPKIHash_Tor3,
  NULL,
};
#define kTorPins \
  kTorAcceptableCerts, \
  kNoRejectedPublicKeys

static const char* const kTwitterComAcceptableCerts[] = {
  kSPKIHash_VeriSignClass1,
  kSPKIHash_VeriSignClass3,
  kSPKIHash_VeriSignClass3_G4,
  kSPKIHash_VeriSignClass4_G3,
  kSPKIHash_VeriSignClass3_G3,
  kSPKIHash_VeriSignClass1_G3,
  kSPKIHash_VeriSignClass2_G3,
  kSPKIHash_VeriSignClass3_G2,
  kSPKIHash_VeriSignClass2_G2,
  kSPKIHash_VeriSignClass3_G5,
  kSPKIHash_VeriSignUniversal,
  kSPKIHash_GeoTrustGlobal,
  kSPKIHash_GeoTrustGlobal2,
  kSPKIHash_GeoTrustUniversal,
  kSPKIHash_GeoTrustUniversal2,
  kSPKIHash_GeoTrustPrimary,
  kSPKIHash_GeoTrustPrimary_G2,
  kSPKIHash_GeoTrustPrimary_G3,
  kSPKIHash_Twitter1,
  NULL,
};
#define kTwitterComPins \
  kTwitterComAcceptableCerts, \
  kNoRejectedPublicKeys

static const char* const kTwitterCDNAcceptableCerts[] = {
  kSPKIHash_VeriSignClass1,
  kSPKIHash_VeriSignClass3,
  kSPKIHash_VeriSignClass3_G4,
  kSPKIHash_VeriSignClass4_G3,
  kSPKIHash_VeriSignClass3_G3,
  kSPKIHash_VeriSignClass1_G3,
  kSPKIHash_VeriSignClass2_G3,
  kSPKIHash_VeriSignClass3_G2,
  kSPKIHash_VeriSignClass2_G2,
  kSPKIHash_VeriSignClass3_G5,
  kSPKIHash_VeriSignUniversal,
  kSPKIHash_GeoTrustGlobal,
  kSPKIHash_GeoTrustGlobal2,
  kSPKIHash_GeoTrustUniversal,
  kSPKIHash_GeoTrustUniversal2,
  kSPKIHash_GeoTrustPrimary,
  kSPKIHash_GeoTrustPrimary_G2,
  kSPKIHash_GeoTrustPrimary_G3,
  kSPKIHash_Twitter1,
  kSPKIHash_Entrust_2048,
  kSPKIHash_Entrust_EV,
  kSPKIHash_Entrust_G2,
  kSPKIHash_Entrust_SSL,
  kSPKIHash_AAACertificateServices,
  kSPKIHash_AddTrustClass1CARoot,
  kSPKIHash_AddTrustExternalCARoot,
  kSPKIHash_AddTrustPublicCARoot,
  kSPKIHash_AddTrustQualifiedCARoot,
  kSPKIHash_COMODOCertificationAuthority,
  kSPKIHash_SecureCertificateServices,
  kSPKIHash_TrustedCertificateServices,
  kSPKIHash_UTNDATACorpSGC,
  kSPKIHash_UTNUSERFirstClientAuthenticationandEmail,
  kSPKIHash_UTNUSERFirstHardware,
  kSPKIHash_UTNUSERFirstObject,
  kSPKIHash_GTECyberTrustGlobalRoot,
  NULL,
};
#define kTwitterCDNPins \
  kTwitterCDNAcceptableCerts, \
  kNoRejectedPublicKeys

static const char* const kTor2webAcceptableCerts[] = {
  kSPKIHash_AlphaSSL_G2,
  kSPKIHash_Tor2web,
  NULL,
};
#define kTor2webPins \
  kTor2webAcceptableCerts, \
  kNoRejectedPublicKeys

#define kNoSpkiPins NULL, NULL

#define kNoTackPins NULL, NULL

static const net::PreloadEntry kPreloadedSTS[] = {
  {true, 23, "pinningtest.appspot.com", false, kTestPins, kNoTackPins},
  {true, 10, "google.com", false, kGooglePins, kNoTackPins},
  {true, 17, "health.google.com", true, kGooglePins, kNoTackPins},
  {true, 19, "checkout.google.com", true, kGooglePins, kNoTackPins},
  {true, 17, "chrome.google.com", true, kGooglePins, kNoTackPins},
  {true, 15, "docs.google.com", true, kGooglePins, kNoTackPins},
  {true, 16, "sites.google.com", true, kGooglePins, kNoTackPins},
  {true, 23, "spreadsheets.google.com", true, kGooglePins, kNoTackPins},
  {false, 20, "appengine.google.com", true, kGooglePins, kNoTackPins},
  {true, 20, "encrypted.google.com", true, kGooglePins, kNoTackPins},
  {true, 19, "accounts.google.com", true, kGooglePins, kNoTackPins},
  {true, 19, "profiles.google.com", true, kGooglePins, kNoTackPins},
  {true, 15, "mail.google.com", true, kGooglePins, kNoTackPins},
  {true, 21, "talkgadget.google.com", true, kGooglePins, kNoTackPins},
  {true, 15, "talk.google.com", true, kGooglePins, kNoTackPins},
  {true, 27, "hostedtalkgadget.google.com", true, kGooglePins, kNoTackPins},
  {true, 15, "plus.google.com", true, kGooglePins, kNoTackPins},
  {true, 17, "script.google.com", true, kGooglePins, kNoTackPins},
  {true, 18, "market.android.com", true, kGooglePins, kNoTackPins},
  {true, 24, "ssl.google-analytics.com", true, kGooglePins, kNoTackPins},
  {true, 16, "drive.google.com", true, kGooglePins, kNoTackPins},
  {true, 14, "googleplex.com", true, kGooglePins, kNoTackPins},
  {true, 17, "groups.google.com", true, kGooglePins, kNoTackPins},
  {true, 15, "apis.google.com", true, kGooglePins, kNoTackPins},
  {true, 30, "chromiumcodereview.appspot.com", true, kGooglePins, kNoTackPins},
  {true, 22, "codereview.appspot.com", true, kGooglePins, kNoTackPins},
  {true, 21, "chart.apis.google.com", false, kGooglePins, kNoTackPins},
  {true, 9, "ytimg.com", false, kGooglePins, kNoTackPins},
  {true, 21, "googleusercontent.com", false, kGooglePins, kNoTackPins},
  {true, 11, "youtube.com", false, kGooglePins, kNoTackPins},
  {true, 14, "googleapis.com", false, kGooglePins, kNoTackPins},
  {true, 20, "googleadservices.com", false, kGooglePins, kNoTackPins},
  {true, 14, "googlecode.com", false, kGooglePins, kNoTackPins},
  {true, 11, "appspot.com", false, kGooglePins, kNoTackPins},
  {true, 21, "googlesyndication.com", false, kGooglePins, kNoTackPins},
  {true, 15, "doubleclick.net", false, kGooglePins, kNoTackPins},
  {true, 15, "ssl.gstatic.com", false, kGooglePins, kNoTackPins},
  {true, 8, "youtu.be", false, kGooglePins, kNoTackPins},
  {true, 11, "android.com", false, kGooglePins, kNoTackPins},
  {true, 18, "googlecommerce.com", false, kGooglePins, kNoTackPins},
  {true, 10, "urchin.com", false, kGooglePins, kNoTackPins},
  {true, 6, "goo.gl", false, kGooglePins, kNoTackPins},
  {true, 4, "g.co", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ac", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ad", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ae", false, kGooglePins, kNoTackPins},
  {true, 9, "google.af", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ag", false, kGooglePins, kNoTackPins},
  {true, 9, "google.am", false, kGooglePins, kNoTackPins},
  {true, 9, "google.as", false, kGooglePins, kNoTackPins},
  {true, 9, "google.at", false, kGooglePins, kNoTackPins},
  {true, 9, "google.az", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ba", false, kGooglePins, kNoTackPins},
  {true, 9, "google.be", false, kGooglePins, kNoTackPins},
  {true, 9, "google.bf", false, kGooglePins, kNoTackPins},
  {true, 9, "google.bg", false, kGooglePins, kNoTackPins},
  {true, 9, "google.bi", false, kGooglePins, kNoTackPins},
  {true, 9, "google.bj", false, kGooglePins, kNoTackPins},
  {true, 9, "google.bs", false, kGooglePins, kNoTackPins},
  {true, 9, "google.by", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ca", false, kGooglePins, kNoTackPins},
  {true, 10, "google.cat", false, kGooglePins, kNoTackPins},
  {true, 9, "google.cc", false, kGooglePins, kNoTackPins},
  {true, 9, "google.cd", false, kGooglePins, kNoTackPins},
  {true, 9, "google.cf", false, kGooglePins, kNoTackPins},
  {true, 9, "google.cg", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ch", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ci", false, kGooglePins, kNoTackPins},
  {true, 9, "google.cl", false, kGooglePins, kNoTackPins},
  {true, 9, "google.cm", false, kGooglePins, kNoTackPins},
  {true, 9, "google.cn", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.ao", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.bw", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.ck", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.cr", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.hu", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.id", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.il", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.im", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.in", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.je", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.jp", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.ke", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.kr", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.ls", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.ma", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.mz", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.nz", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.th", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.tz", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.ug", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.uk", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.uz", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.ve", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.vi", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.za", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.zm", false, kGooglePins, kNoTackPins},
  {true, 12, "google.co.zw", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.af", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ag", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ai", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ar", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.au", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.bd", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.bh", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.bn", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.bo", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.br", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.by", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.bz", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.cn", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.co", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.cu", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.cy", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.do", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ec", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.eg", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.et", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.fj", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ge", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.gh", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.gi", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.gr", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.gt", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.hk", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.iq", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.jm", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.jo", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.kh", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.kw", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.lb", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ly", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.mt", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.mx", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.my", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.na", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.nf", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ng", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ni", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.np", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.nr", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.om", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.pa", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.pe", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ph", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.pk", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.pl", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.pr", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.py", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.qa", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ru", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.sa", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.sb", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.sg", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.sl", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.sv", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.tj", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.tn", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.tr", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.tw", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ua", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.uy", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.vc", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.ve", false, kGooglePins, kNoTackPins},
  {true, 13, "google.com.vn", false, kGooglePins, kNoTackPins},
  {true, 9, "google.cv", false, kGooglePins, kNoTackPins},
  {true, 9, "google.cz", false, kGooglePins, kNoTackPins},
  {true, 9, "google.de", false, kGooglePins, kNoTackPins},
  {true, 9, "google.dj", false, kGooglePins, kNoTackPins},
  {true, 9, "google.dk", false, kGooglePins, kNoTackPins},
  {true, 9, "google.dm", false, kGooglePins, kNoTackPins},
  {true, 9, "google.dz", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ee", false, kGooglePins, kNoTackPins},
  {true, 9, "google.es", false, kGooglePins, kNoTackPins},
  {true, 9, "google.fi", false, kGooglePins, kNoTackPins},
  {true, 9, "google.fm", false, kGooglePins, kNoTackPins},
  {true, 9, "google.fr", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ga", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ge", false, kGooglePins, kNoTackPins},
  {true, 9, "google.gg", false, kGooglePins, kNoTackPins},
  {true, 9, "google.gl", false, kGooglePins, kNoTackPins},
  {true, 9, "google.gm", false, kGooglePins, kNoTackPins},
  {true, 9, "google.gp", false, kGooglePins, kNoTackPins},
  {true, 9, "google.gr", false, kGooglePins, kNoTackPins},
  {true, 9, "google.gy", false, kGooglePins, kNoTackPins},
  {true, 9, "google.hk", false, kGooglePins, kNoTackPins},
  {true, 9, "google.hn", false, kGooglePins, kNoTackPins},
  {true, 9, "google.hr", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ht", false, kGooglePins, kNoTackPins},
  {true, 9, "google.hu", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ie", false, kGooglePins, kNoTackPins},
  {true, 9, "google.im", false, kGooglePins, kNoTackPins},
  {true, 11, "google.info", false, kGooglePins, kNoTackPins},
  {true, 9, "google.iq", false, kGooglePins, kNoTackPins},
  {true, 9, "google.is", false, kGooglePins, kNoTackPins},
  {true, 9, "google.it", false, kGooglePins, kNoTackPins},
  {true, 12, "google.it.ao", false, kGooglePins, kNoTackPins},
  {true, 9, "google.je", false, kGooglePins, kNoTackPins},
  {true, 9, "google.jo", false, kGooglePins, kNoTackPins},
  {true, 11, "google.jobs", false, kGooglePins, kNoTackPins},
  {true, 9, "google.jp", false, kGooglePins, kNoTackPins},
  {true, 9, "google.kg", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ki", false, kGooglePins, kNoTackPins},
  {true, 9, "google.kz", false, kGooglePins, kNoTackPins},
  {true, 9, "google.la", false, kGooglePins, kNoTackPins},
  {true, 9, "google.li", false, kGooglePins, kNoTackPins},
  {true, 9, "google.lk", false, kGooglePins, kNoTackPins},
  {true, 9, "google.lt", false, kGooglePins, kNoTackPins},
  {true, 9, "google.lu", false, kGooglePins, kNoTackPins},
  {true, 9, "google.lv", false, kGooglePins, kNoTackPins},
  {true, 9, "google.md", false, kGooglePins, kNoTackPins},
  {true, 9, "google.me", false, kGooglePins, kNoTackPins},
  {true, 9, "google.mg", false, kGooglePins, kNoTackPins},
  {true, 9, "google.mk", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ml", false, kGooglePins, kNoTackPins},
  {true, 9, "google.mn", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ms", false, kGooglePins, kNoTackPins},
  {true, 9, "google.mu", false, kGooglePins, kNoTackPins},
  {true, 9, "google.mv", false, kGooglePins, kNoTackPins},
  {true, 9, "google.mw", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ne", false, kGooglePins, kNoTackPins},
  {true, 12, "google.ne.jp", false, kGooglePins, kNoTackPins},
  {true, 10, "google.net", false, kGooglePins, kNoTackPins},
  {true, 9, "google.nl", false, kGooglePins, kNoTackPins},
  {true, 9, "google.no", false, kGooglePins, kNoTackPins},
  {true, 9, "google.nr", false, kGooglePins, kNoTackPins},
  {true, 9, "google.nu", false, kGooglePins, kNoTackPins},
  {true, 13, "google.off.ai", false, kGooglePins, kNoTackPins},
  {true, 9, "google.pk", false, kGooglePins, kNoTackPins},
  {true, 9, "google.pl", false, kGooglePins, kNoTackPins},
  {true, 9, "google.pn", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ps", false, kGooglePins, kNoTackPins},
  {true, 9, "google.pt", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ro", false, kGooglePins, kNoTackPins},
  {true, 9, "google.rs", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ru", false, kGooglePins, kNoTackPins},
  {true, 9, "google.rw", false, kGooglePins, kNoTackPins},
  {true, 9, "google.sc", false, kGooglePins, kNoTackPins},
  {true, 9, "google.se", false, kGooglePins, kNoTackPins},
  {true, 9, "google.sh", false, kGooglePins, kNoTackPins},
  {true, 9, "google.si", false, kGooglePins, kNoTackPins},
  {true, 9, "google.sk", false, kGooglePins, kNoTackPins},
  {true, 9, "google.sm", false, kGooglePins, kNoTackPins},
  {true, 9, "google.sn", false, kGooglePins, kNoTackPins},
  {true, 9, "google.so", false, kGooglePins, kNoTackPins},
  {true, 9, "google.st", false, kGooglePins, kNoTackPins},
  {true, 9, "google.td", false, kGooglePins, kNoTackPins},
  {true, 9, "google.tg", false, kGooglePins, kNoTackPins},
  {true, 9, "google.tk", false, kGooglePins, kNoTackPins},
  {true, 9, "google.tl", false, kGooglePins, kNoTackPins},
  {true, 9, "google.tm", false, kGooglePins, kNoTackPins},
  {true, 9, "google.tn", false, kGooglePins, kNoTackPins},
  {true, 9, "google.to", false, kGooglePins, kNoTackPins},
  {true, 9, "google.tp", false, kGooglePins, kNoTackPins},
  {true, 9, "google.tt", false, kGooglePins, kNoTackPins},
  {true, 9, "google.us", false, kGooglePins, kNoTackPins},
  {true, 9, "google.uz", false, kGooglePins, kNoTackPins},
  {true, 9, "google.vg", false, kGooglePins, kNoTackPins},
  {true, 9, "google.vu", false, kGooglePins, kNoTackPins},
  {true, 9, "google.ws", false, kGooglePins, kNoTackPins},
  {true, 21, "learn.doubleclick.net", false, kNoSpkiPins, kNoTackPins},
  {false, 14, "www.paypal.com", true, kNoSpkiPins, kNoTackPins},
  {false, 14, "www.elanex.biz", true, kNoSpkiPins, kNoTackPins},
  {true, 10, "jottit.com", true, kNoSpkiPins, kNoTackPins},
  {true, 17, "sunshinepress.org", true, kNoSpkiPins, kNoTackPins},
  {false, 19, "www.noisebridge.net", true, kNoSpkiPins, kNoTackPins},
  {false, 8, "neg9.org", true, kNoSpkiPins, kNoTackPins},
  {true, 10, "riseup.net", true, kNoSpkiPins, kNoTackPins},
  {false, 9, "factor.cc", true, kNoSpkiPins, kNoTackPins},
  {false, 20, "members.mayfirst.org", true, kNoSpkiPins, kNoTackPins},
  {false, 20, "support.mayfirst.org", true, kNoSpkiPins, kNoTackPins},
  {false, 15, "id.mayfirst.org", true, kNoSpkiPins, kNoTackPins},
  {false, 18, "lists.mayfirst.org", true, kNoSpkiPins, kNoTackPins},
  {false, 26, "aladdinschools.appspot.com", true, kNoSpkiPins, kNoTackPins},
  {true, 12, "ottospora.nl", true, kNoSpkiPins, kNoTackPins},
  {false, 23, "www.paycheckrecords.com", true, kNoSpkiPins, kNoTackPins},
  {false, 12, "lastpass.com", true, kNoSpkiPins, kNoTackPins},
  {false, 16, "www.lastpass.com", true, kNoSpkiPins, kNoTackPins},
  {true, 12, "keyerror.com", true, kNoSpkiPins, kNoTackPins},
  {false, 11, "entropia.de", true, kNoSpkiPins, kNoTackPins},
  {false, 15, "www.entropia.de", true, kNoSpkiPins, kNoTackPins},
  {true, 9, "romab.com", true, kNoSpkiPins, kNoTackPins},
  {false, 14, "logentries.com", true, kNoSpkiPins, kNoTackPins},
  {false, 18, "www.logentries.com", true, kNoSpkiPins, kNoTackPins},
  {true, 10, "stripe.com", true, kNoSpkiPins, kNoTackPins},
  {true, 25, "cloudsecurityalliance.org", true, kNoSpkiPins, kNoTackPins},
  {true, 13, "login.sapo.pt", true, kNoSpkiPins, kNoTackPins},
  {true, 17, "mattmccutchen.net", true, kNoSpkiPins, kNoTackPins},
  {true, 9, "betnet.fr", true, kNoSpkiPins, kNoTackPins},
  {true, 11, "uprotect.it", true, kNoSpkiPins, kNoTackPins},
  {false, 12, "squareup.com", true, kNoSpkiPins, kNoTackPins},
  {true, 7, "cert.se", true, kNoSpkiPins, kNoTackPins},
  {true, 9, "crypto.is", true, kNoSpkiPins, kNoTackPins},
  {true, 18, "simon.butcher.name", true, kNoSpkiPins, kNoTackPins},
  {true, 8, "linx.net", true, kNoSpkiPins, kNoTackPins},
  {false, 11, "dropcam.com", true, kNoSpkiPins, kNoTackPins},
  {false, 15, "www.dropcam.com", true, kNoSpkiPins, kNoTackPins},
  {true, 28, "ebanking.indovinabank.com.vn", true, kNoSpkiPins, kNoTackPins},
  {false, 11, "epoxate.com", true, kNoSpkiPins, kNoTackPins},
  {false, 14, "torproject.org", true, kTorPins, kNoTackPins},
  {true, 19, "blog.torproject.org", true, kTorPins, kNoTackPins},
  {true, 20, "check.torproject.org", true, kTorPins, kNoTackPins},
  {true, 18, "www.torproject.org", true, kTorPins, kNoTackPins},
  {true, 20, "www.moneybookers.com", true, kNoSpkiPins, kNoTackPins},
  {false, 15, "ledgerscope.net", true, kNoSpkiPins, kNoTackPins},
  {false, 19, "www.ledgerscope.net", true, kNoSpkiPins, kNoTackPins},
  {false, 8, "kyps.net", true, kNoSpkiPins, kNoTackPins},
  {false, 12, "www.kyps.net", true, kNoSpkiPins, kNoTackPins},
  {true, 15, "app.recurly.com", true, kNoSpkiPins, kNoTackPins},
  {true, 15, "api.recurly.com", true, kNoSpkiPins, kNoTackPins},
  {false, 11, "greplin.com", true, kNoSpkiPins, kNoTackPins},
  {false, 15, "www.greplin.com", true, kNoSpkiPins, kNoTackPins},
  {true, 25, "luneta.nearbuysystems.com", true, kNoSpkiPins, kNoTackPins},
  {true, 10, "ubertt.org", true, kNoSpkiPins, kNoTackPins},
  {true, 7, "pixi.me", true, kNoSpkiPins, kNoTackPins},
  {true, 12, "grepular.com", true, kNoSpkiPins, kNoTackPins},
  {false, 14, "mydigipass.com", true, kNoSpkiPins, kNoTackPins},
  {false, 18, "www.mydigipass.com", true, kNoSpkiPins, kNoTackPins},
  {false, 24, "developer.mydigipass.com", true, kNoSpkiPins, kNoTackPins},
  {false, 28, "www.developer.mydigipass.com", true, kNoSpkiPins, kNoTackPins},
  {false, 22, "sandbox.mydigipass.com", true, kNoSpkiPins, kNoTackPins},
  {false, 26, "www.sandbox.mydigipass.com", true, kNoSpkiPins, kNoTackPins},
  {true, 10, "crypto.cat", true, kNoSpkiPins, kNoTackPins},
  {true, 23, "bigshinylock.minazo.net", true, kNoSpkiPins, kNoTackPins},
  {true, 8, "crate.io", true, kNoSpkiPins, kNoTackPins},
  {false, 11, "twitter.com", false, kTwitterComPins, kNoTackPins},
  {true, 15, "www.twitter.com", false, kTwitterComPins, kNoTackPins},
  {true, 15, "api.twitter.com", false, kTwitterCDNPins, kNoTackPins},
  {true, 17, "oauth.twitter.com", false, kTwitterComPins, kNoTackPins},
  {true, 18, "mobile.twitter.com", false, kTwitterComPins, kNoTackPins},
  {true, 15, "dev.twitter.com", false, kTwitterComPins, kNoTackPins},
  {true, 20, "business.twitter.com", false, kTwitterComPins, kNoTackPins},
  {true, 20, "platform.twitter.com", false, kTwitterCDNPins, kNoTackPins},
  {true, 13, "si0.twimg.com", false, kTwitterCDNPins, kNoTackPins},
  {true, 21, "twimg0-a.akamaihd.net", false, kTwitterCDNPins, kNoTackPins},
  {true, 20, "braintreegateway.com", true, kNoSpkiPins, kNoTackPins},
  {false, 21, "braintreepayments.com", true, kNoSpkiPins, kNoTackPins},
  {false, 25, "www.braintreepayments.com", true, kNoSpkiPins, kNoTackPins},
  {false, 22, "emailprivacytester.com", true, kNoSpkiPins, kNoTackPins},
  {true, 11, "tor2web.org", false, kTor2webPins, kNoTackPins},
  {true, 23, "business.medbank.com.mt", true, kNoSpkiPins, kNoTackPins},
  {true, 12, "arivo.com.br", true, kNoSpkiPins, kNoTackPins},
  {true, 19, "www.apollo-auto.com", true, kNoSpkiPins, kNoTackPins},
  {true, 13, "www.cueup.com", true, kNoSpkiPins, kNoTackPins},
  {false, 9, "jitsi.org", true, kNoSpkiPins, kNoTackPins},
  {false, 13, "www.jitsi.org", true, kNoSpkiPins, kNoTackPins},
  {false, 18, "download.jitsi.org", true, kNoSpkiPins, kNoTackPins},
  {true, 6, "sol.io", true, kNoSpkiPins, kNoTackPins},
  {false, 12, "irccloud.com", true, kNoSpkiPins, kNoTackPins},
  {false, 16, "www.irccloud.com", true, kNoSpkiPins, kNoTackPins},
  {false, 18, "alpha.irccloud.com", true, kNoSpkiPins, kNoTackPins},
  {true, 9, "passwd.io", true, kNoSpkiPins, kNoTackPins},
  {true, 13, "browserid.org", true, kNoSpkiPins, kNoTackPins},
  {true, 17, "login.persona.org", true, kNoSpkiPins, kNoTackPins},
  {false, 11, "neonisi.com", true, kNoSpkiPins, kNoTackPins},
  {true, 15, "www.neonisi.com", true, kNoSpkiPins, kNoTackPins},
  {true, 17, "shops.neonisi.com", true, kNoSpkiPins, kNoTackPins},
  {true, 15, "piratenlogin.de", true, kNoSpkiPins, kNoTackPins},
  {true, 13, "howrandom.org", true, kNoSpkiPins, kNoTackPins},
  {false, 11, "intercom.io", true, kNoSpkiPins, kNoTackPins},
  {false, 15, "api.intercom.io", true, kNoSpkiPins, kNoTackPins},
  {false, 15, "www.intercom.io", true, kNoSpkiPins, kNoTackPins},
  {true, 15, "fatzebra.com.au", true, kNoSpkiPins, kNoTackPins},
  {true, 16, "csawctf.poly.edu", true, kNoSpkiPins, kNoTackPins},
  {false, 16, "makeyourlaws.org", true, kNoSpkiPins, kNoTackPins},
  {false, 20, "www.makeyourlaws.org", true, kNoSpkiPins, kNoTackPins},
  {true, 14, "iop.intuit.com", true, kNoSpkiPins, kNoTackPins},
  {true, 7, "tack.io", true, kNoSpkiPins, kNoTackPins},
  {false, 12, "test.tack.io", false, kNoSpkiPins, NULL, "j6det.kfbj5.oweph.mdyxi.wvbch"},
  {false, 12, "test.tack.io", false, kGooglePins, kNoTackPins},
};
static const size_t kNumPreloadedSTS = ARRAYSIZE_UNSAFE(kPreloadedSTS);

static const net::PreloadEntry kPreloadedSNISTS[] = {
  {false, 9, "gmail.com", true, kGooglePins, kNoTackPins},
  {false, 14, "googlemail.com", true, kGooglePins, kNoTackPins},
  {false, 13, "www.gmail.com", true, kGooglePins, kNoTackPins},
  {false, 18, "www.googlemail.com", true, kGooglePins, kNoTackPins},
  {true, 20, "google-analytics.com", false, kGooglePins, kNoTackPins},
  {true, 16, "googlegroups.com", false, kGooglePins, kNoTackPins},
};
static const size_t kNumPreloadedSNISTS = ARRAYSIZE_UNSAFE(kPreloadedSNISTS);

#endif // NET_BASE_TRANSPORT_SECURITY_STATE_STATIC_H_
