// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is automatically generated by transport_security_state_static_generate.go

#ifndef NET_BASE_TRANSPORT_SECURITY_STATE_STATIC_H_
#define NET_BASE_TRANSPORT_SECURITY_STATE_STATIC_H_

// These are TACK key fingerprints and their min_generation values.

static const struct PreloadTackKey kPreloadedTackKeys[] = {
  {"6i7l7.gw7zx.kuza6.skvzy.6alwa", 3},
  {"j6det.kfbj5.oweph.mdyxi.wvbch", 0},
  {"k2wgv.l24nx.yiqyc.zjir5.md474", 255},
};

// These are SubjectPublicKeyInfo hashes for public key pinning. The
// hashes are base64 encoded, SHA1 digests.

static const char kSPKIHash_TestSPKI[] =
    "sha1/AAAAAAAAAAAAAAAAAAAAAAAAAAA=";

static const char kSPKIHash_VeriSignClass3[] =
    "sha1/4n972HfV354KP560yw4uqe/baXc=";

static const char kSPKIHash_VeriSignClass3_G3[] =
    "sha1/IvGeLsbqzPxdI0b0wuj2xVTdXgc=";

static const char kSPKIHash_Google1024[] =
    "sha1/QMVAHW+MuvCLAO3vse6H0AWzuc0=";

static const char kSPKIHash_Google2048[] =
    "sha1/AbkhxY0L343gKf+cki7NVWp+ozk=";

static const char kSPKIHash_EquifaxSecureCA[] =
    "sha1/SOZo+SvSspXXR9gjIBBPM5iQn9Q=";

static const char kSPKIHash_Aetna[] =
    "sha1/klKqFN6/gK4wqtlOYDhwJKVDLxo=";

static const char kSPKIHash_GeoTrustGlobal[] =
    "sha1/wHqYaI2J+6sFZAwRfap9ZbjKzE4=";

static const char kSPKIHash_GeoTrustPrimary[] =
    "sha1/sBmJ5+/7Sq/LFI9YRjl2IkFQ4bo=";

static const char kSPKIHash_Intel[] =
    "sha1/DsYq91myCBCQJW/D3f2KZjEwK8U=";

static const char kSPKIHash_TCTrustCenter[] =
    "sha1/gzuEEAB/bkqdQS3EIjk2by7lW+k=";

static const char kSPKIHash_Vodafone[] =
    "sha1/DX/hXFUUNmiZ/EDWIgjvIuvRFRw=";

static const char kSPKIHash_RapidSSL[] =
    "sha1/o5OZxATDsgmwgcIfIWIneMJ0jkw=";

static const char kSPKIHash_DigiCertEVRoot[] =
    "sha1/gzF+YoVCU9bXeDGQ7JGQVumRueM=";

static const char kSPKIHash_Tor1[] =
    "sha1/juNxSTv9UANmpC9kF5GKpmWNx3Y=";

static const char kSPKIHash_Tor2[] =
    "sha1/lia43lPolzSPVIq34Dw57uYcLD8=";

static const char kSPKIHash_Tor3[] =
    "sha1/rzEyQIKOh77j87n5bjWUNguXF8Y=";

static const char kSPKIHash_VeriSignClass1[] =
    "sha1/I0PRSKJViZuUfUYaeX7ATP7RcLc=";

static const char kSPKIHash_VeriSignClass3_G4[] =
    "sha1/7WYxNdMb1OymFMQp4xkGn5TBJlA=";

static const char kSPKIHash_VeriSignClass4_G3[] =
    "sha1/PANDaGiVHPNpKri0Jtq6j+ki5b0=";

static const char kSPKIHash_VeriSignClass1_G3[] =
    "sha1/VRmyeKyygdftp6vBg5nDu2kEJLU=";

static const char kSPKIHash_VeriSignClass2_G3[] =
    "sha1/Wr7Fddyu87COJxlD/H8lDD32YeM=";

static const char kSPKIHash_VeriSignClass3_G2[] =
    "sha1/GiG0lStik84Ys2XsnA6TTLOB5tQ=";

static const char kSPKIHash_VeriSignClass2_G2[] =
    "sha1/Eje6RRfurSkm/cHN/r7t8t7ZFFw=";

static const char kSPKIHash_VeriSignClass3_G5[] =
    "sha1/sYEIGhmkwJQf+uiVKMEkyZs0rMc=";

static const char kSPKIHash_VeriSignUniversal[] =
    "sha1/u8I+KQuzKHcdrT6iTb30I70GsD0=";

static const char kSPKIHash_Twitter1[] =
    "sha1/Vv7zwhR9TtOIN/29MFI4cgHld40=";

static const char kSPKIHash_GeoTrustGlobal2[] =
    "sha1/cTg28gIxU0crbrplRqkQFVggBQk=";

static const char kSPKIHash_GeoTrustUniversal[] =
    "sha1/h+hbY1PGI6MSjLD/u/VR/lmADiI=";

static const char kSPKIHash_GeoTrustUniversal2[] =
    "sha1/Xk9ThoXdT57KX9wNRW99UbHcm3s=";

static const char kSPKIHash_GeoTrustPrimary_G2[] =
    "sha1/vb6nG6txV/nkddlU0rcngBqCJoI=";

static const char kSPKIHash_GeoTrustPrimary_G3[] =
    "sha1/nKmNAK90Dd2BgNITRaWLjy6UONY=";

static const char kSPKIHash_Entrust_2048[] =
    "sha1/VeSB0RGAvtiJuQijMfmhJAkWuXA=";

static const char kSPKIHash_Entrust_EV[] =
    "sha1/ukKwgYhTiB2GY71MwF4I/upuu3c=";

static const char kSPKIHash_Entrust_G2[] =
    "sha1/qzDTr0vY8WtYae5FaSnahLhzlIg=";

static const char kSPKIHash_Entrust_SSL[] =
    "sha1/8BdiE1U9s/8KAGv7UISX8+1i0Bo=";

static const char kSPKIHash_AAACertificateServices[] =
    "sha1/xDAoxdPjCAwQRIssd7okU5dgu/k=";

static const char kSPKIHash_AddTrustClass1CARoot[] =
    "sha1/i9vXzKBoU0IW9MErJUT8Apyli0c=";

static const char kSPKIHash_AddTrustExternalCARoot[] =
    "sha1/T5x9IXmcrQ7YuQxXnxoCmeeQ84c=";

static const char kSPKIHash_AddTrustPublicCARoot[] =
    "sha1/qFdl1ugyyMUZY3Namhd0OoHf7i4=";

static const char kSPKIHash_AddTrustQualifiedCARoot[] =
    "sha1/vOS3IxJVmOVjQRkcUOS2R8J2Bdc=";

static const char kSPKIHash_COMODOCertificationAuthority[] =
    "sha1/EeSR0cnkwOuazs9zVF3h8agwPsM=";

static const char kSPKIHash_SecureCertificateServices[] =
    "sha1/PLQahC71XPIaPaVKyNG+OQh2N7w=";

static const char kSPKIHash_TrustedCertificateServices[] =
    "sha1//nLI678ML7sOJhOTkzwsqY3cJJQ=";

static const char kSPKIHash_UTNDATACorpSGC[] =
    "sha1/UzLRs89/+uDxoF2FTpLSnkUdtE8=";

static const char kSPKIHash_UTNUSERFirstClientAuthenticationandEmail[] =
    "sha1/iYJnfcSdJnAAS7RQSHzePa4Ebn0=";

static const char kSPKIHash_UTNUSERFirstHardware[] =
    "sha1/oXJfJhsomEOVXQc31YWWnUvSw0U=";

static const char kSPKIHash_UTNUSERFirstObject[] =
    "sha1/2u1kdBScFDyr3ZmpvVsoTYs8ydg=";

static const char kSPKIHash_GTECyberTrustGlobalRoot[] =
    "sha1/WXkS3mF11m/EI7d3E3THlt5viHI=";

static const char kSPKIHash_Tor2web[] =
    "sha1/GeW1hxvUgy7I9ZSX/sZe+0jjM7E=";

static const char kSPKIHash_AlphaSSL_G2[] =
    "sha1/5STpjjF9yPytkFN8kecNpHCTkF8=";

// The following is static data describing the hosts that are hardcoded with
// certificate pins or HSTS information.

// kNoRejectedPublicKeys is a placeholder for when no public keys are rejected.
static const char* const kNoRejectedPublicKeys[] = {
  NULL,
};

static const char* const kTestAcceptableCerts[] = {
  kSPKIHash_TestSPKI,
  NULL,
};
#define kTestPins \
  kTestAcceptableCerts, \
  kNoRejectedPublicKeys, \

static const char* const kGoogleAcceptableCerts[] = {
  kSPKIHash_VeriSignClass3,
  kSPKIHash_VeriSignClass3_G3,
  kSPKIHash_Google1024,
  kSPKIHash_Google2048,
  kSPKIHash_EquifaxSecureCA,
  NULL,
};
static const char* const kGoogleRejectedCerts[] = {
  kSPKIHash_Aetna,
  kSPKIHash_Intel,
  kSPKIHash_TCTrustCenter,
  kSPKIHash_Vodafone,
  NULL,
};
#define kGooglePins \
  kGoogleAcceptableCerts, \
  kGoogleRejectedCerts, \

static const char* const kTorAcceptableCerts[] = {
  kSPKIHash_RapidSSL,
  kSPKIHash_DigiCertEVRoot,
  kSPKIHash_Tor1,
  kSPKIHash_Tor2,
  kSPKIHash_Tor3,
  NULL,
};
#define kTorPins \
  kTorAcceptableCerts, \
  kNoRejectedPublicKeys, \

static const char* const kTwitterComAcceptableCerts[] = {
  kSPKIHash_VeriSignClass1,
  kSPKIHash_VeriSignClass3,
  kSPKIHash_VeriSignClass3_G4,
  kSPKIHash_VeriSignClass4_G3,
  kSPKIHash_VeriSignClass3_G3,
  kSPKIHash_VeriSignClass1_G3,
  kSPKIHash_VeriSignClass2_G3,
  kSPKIHash_VeriSignClass3_G2,
  kSPKIHash_VeriSignClass2_G2,
  kSPKIHash_VeriSignClass3_G5,
  kSPKIHash_VeriSignUniversal,
  kSPKIHash_GeoTrustGlobal,
  kSPKIHash_GeoTrustGlobal2,
  kSPKIHash_GeoTrustUniversal,
  kSPKIHash_GeoTrustUniversal2,
  kSPKIHash_GeoTrustPrimary,
  kSPKIHash_GeoTrustPrimary_G2,
  kSPKIHash_GeoTrustPrimary_G3,
  kSPKIHash_Twitter1,
  NULL,
};
#define kTwitterComPins \
  kTwitterComAcceptableCerts, \
  kNoRejectedPublicKeys, \

static const char* const kTwitterCDNAcceptableCerts[] = {
  kSPKIHash_VeriSignClass1,
  kSPKIHash_VeriSignClass3,
  kSPKIHash_VeriSignClass3_G4,
  kSPKIHash_VeriSignClass4_G3,
  kSPKIHash_VeriSignClass3_G3,
  kSPKIHash_VeriSignClass1_G3,
  kSPKIHash_VeriSignClass2_G3,
  kSPKIHash_VeriSignClass3_G2,
  kSPKIHash_VeriSignClass2_G2,
  kSPKIHash_VeriSignClass3_G5,
  kSPKIHash_VeriSignUniversal,
  kSPKIHash_GeoTrustGlobal,
  kSPKIHash_GeoTrustGlobal2,
  kSPKIHash_GeoTrustUniversal,
  kSPKIHash_GeoTrustUniversal2,
  kSPKIHash_GeoTrustPrimary,
  kSPKIHash_GeoTrustPrimary_G2,
  kSPKIHash_GeoTrustPrimary_G3,
  kSPKIHash_Twitter1,
  kSPKIHash_Entrust_2048,
  kSPKIHash_Entrust_EV,
  kSPKIHash_Entrust_G2,
  kSPKIHash_Entrust_SSL,
  kSPKIHash_AAACertificateServices,
  kSPKIHash_AddTrustClass1CARoot,
  kSPKIHash_AddTrustExternalCARoot,
  kSPKIHash_AddTrustPublicCARoot,
  kSPKIHash_AddTrustQualifiedCARoot,
  kSPKIHash_COMODOCertificationAuthority,
  kSPKIHash_SecureCertificateServices,
  kSPKIHash_TrustedCertificateServices,
  kSPKIHash_UTNDATACorpSGC,
  kSPKIHash_UTNUSERFirstClientAuthenticationandEmail,
  kSPKIHash_UTNUSERFirstHardware,
  kSPKIHash_UTNUSERFirstObject,
  kSPKIHash_GTECyberTrustGlobalRoot,
  NULL,
};
#define kTwitterCDNPins \
  kTwitterCDNAcceptableCerts, \
  kNoRejectedPublicKeys, \

static const char* const kTor2webAcceptableCerts[] = {
  kSPKIHash_AlphaSSL_G2,
  kSPKIHash_Tor2web,
  NULL,
};
#define kTor2webPins \
  kTor2webAcceptableCerts, \
  kNoRejectedPublicKeys, \

#define kNoPins {\
  NULL, NULL, \
}

static const struct PreloadEntry kPreloadedSTS[] = {
  {23, true, "pinningtest.appspot.com", false, kTestPins, "", DOMAIN_APPSPOT_COM },
  {10, true, "google.com", false, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {17, true, "health.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {19, true, "checkout.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {17, true, "chrome.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {15, true, "docs.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {16, true, "sites.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {23, true, "spreadsheets.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {20, false, "appengine.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {20, true, "encrypted.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {19, true, "accounts.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {19, true, "profiles.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {15, true, "mail.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {21, true, "talkgadget.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {15, true, "talk.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {27, true, "hostedtalkgadget.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {15, true, "plus.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {17, true, "script.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {18, true, "market.android.com", true, kGooglePins, "", DOMAIN_ANDROID_COM },
  {24, true, "ssl.google-analytics.com", true, kGooglePins, "", DOMAIN_GOOGLE_ANALYTICS_COM },
  {16, true, "drive.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {14, true, "googleplex.com", true, kGooglePins, "", DOMAIN_GOOGLEPLEX_COM },
  {17, true, "groups.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {15, true, "apis.google.com", true, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {30, true, "chromiumcodereview.appspot.com", true, kGooglePins, "", DOMAIN_APPSPOT_COM },
  {22, true, "codereview.appspot.com", true, kGooglePins, "", DOMAIN_APPSPOT_COM },
  {21, true, "chart.apis.google.com", false, kGooglePins, "", DOMAIN_GOOGLE_COM },
  {9, true, "ytimg.com", false, kGooglePins, "", DOMAIN_YTIMG_COM },
  {21, true, "googleusercontent.com", false, kGooglePins, "", DOMAIN_GOOGLEUSERCONTENT_COM },
  {11, true, "youtube.com", false, kGooglePins, "", DOMAIN_YOUTUBE_COM },
  {14, true, "googleapis.com", false, kGooglePins, "", DOMAIN_GOOGLEAPIS_COM },
  {20, true, "googleadservices.com", false, kGooglePins, "", DOMAIN_GOOGLEADSERVICES_COM },
  {14, true, "googlecode.com", false, kGooglePins, "", DOMAIN_GOOGLECODE_COM },
  {11, true, "appspot.com", false, kGooglePins, "", DOMAIN_APPSPOT_COM },
  {21, true, "googlesyndication.com", false, kGooglePins, "", DOMAIN_GOOGLESYNDICATION_COM },
  {15, true, "doubleclick.net", false, kGooglePins, "", DOMAIN_DOUBLECLICK_NET },
  {15, true, "ssl.gstatic.com", false, kGooglePins, "", DOMAIN_GSTATIC_COM },
  {8, true, "youtu.be", false, kGooglePins, "", DOMAIN_YOUTU_BE },
  {11, true, "android.com", false, kGooglePins, "", DOMAIN_ANDROID_COM },
  {18, true, "googlecommerce.com", false, kGooglePins, "", DOMAIN_GOOGLECOMMERCE_COM },
  {10, true, "urchin.com", false, kGooglePins, "", DOMAIN_URCHIN_COM },
  {6, true, "goo.gl", false, kGooglePins, "", DOMAIN_GOO_GL },
  {4, true, "g.co", false, kGooglePins, "", DOMAIN_G_CO },
  {9, true, "google.ac", false, kGooglePins, "", DOMAIN_GOOGLE_AC },
  {9, true, "google.ad", false, kGooglePins, "", DOMAIN_GOOGLE_AD },
  {9, true, "google.ae", false, kGooglePins, "", DOMAIN_GOOGLE_AE },
  {9, true, "google.af", false, kGooglePins, "", DOMAIN_GOOGLE_AF },
  {9, true, "google.ag", false, kGooglePins, "", DOMAIN_GOOGLE_AG },
  {9, true, "google.am", false, kGooglePins, "", DOMAIN_GOOGLE_AM },
  {9, true, "google.as", false, kGooglePins, "", DOMAIN_GOOGLE_AS },
  {9, true, "google.at", false, kGooglePins, "", DOMAIN_GOOGLE_AT },
  {9, true, "google.az", false, kGooglePins, "", DOMAIN_GOOGLE_AZ },
  {9, true, "google.ba", false, kGooglePins, "", DOMAIN_GOOGLE_BA },
  {9, true, "google.be", false, kGooglePins, "", DOMAIN_GOOGLE_BE },
  {9, true, "google.bf", false, kGooglePins, "", DOMAIN_GOOGLE_BF },
  {9, true, "google.bg", false, kGooglePins, "", DOMAIN_GOOGLE_BG },
  {9, true, "google.bi", false, kGooglePins, "", DOMAIN_GOOGLE_BI },
  {9, true, "google.bj", false, kGooglePins, "", DOMAIN_GOOGLE_BJ },
  {9, true, "google.bs", false, kGooglePins, "", DOMAIN_GOOGLE_BS },
  {9, true, "google.by", false, kGooglePins, "", DOMAIN_GOOGLE_BY },
  {9, true, "google.ca", false, kGooglePins, "", DOMAIN_GOOGLE_CA },
  {10, true, "google.cat", false, kGooglePins, "", DOMAIN_GOOGLE_CAT },
  {9, true, "google.cc", false, kGooglePins, "", DOMAIN_GOOGLE_CC },
  {9, true, "google.cd", false, kGooglePins, "", DOMAIN_GOOGLE_CD },
  {9, true, "google.cf", false, kGooglePins, "", DOMAIN_GOOGLE_CF },
  {9, true, "google.cg", false, kGooglePins, "", DOMAIN_GOOGLE_CG },
  {9, true, "google.ch", false, kGooglePins, "", DOMAIN_GOOGLE_CH },
  {9, true, "google.ci", false, kGooglePins, "", DOMAIN_GOOGLE_CI },
  {9, true, "google.cl", false, kGooglePins, "", DOMAIN_GOOGLE_CL },
  {9, true, "google.cm", false, kGooglePins, "", DOMAIN_GOOGLE_CM },
  {9, true, "google.cn", false, kGooglePins, "", DOMAIN_GOOGLE_CN },
  {12, true, "google.co.ao", false, kGooglePins, "", DOMAIN_CO_AO },
  {12, true, "google.co.bw", false, kGooglePins, "", DOMAIN_CO_BW },
  {12, true, "google.co.ck", false, kGooglePins, "", DOMAIN_CO_CK },
  {12, true, "google.co.cr", false, kGooglePins, "", DOMAIN_CO_CR },
  {12, true, "google.co.hu", false, kGooglePins, "", DOMAIN_CO_HU },
  {12, true, "google.co.id", false, kGooglePins, "", DOMAIN_CO_ID },
  {12, true, "google.co.il", false, kGooglePins, "", DOMAIN_CO_IL },
  {12, true, "google.co.im", false, kGooglePins, "", DOMAIN_CO_IM },
  {12, true, "google.co.in", false, kGooglePins, "", DOMAIN_CO_IN },
  {12, true, "google.co.je", false, kGooglePins, "", DOMAIN_CO_JE },
  {12, true, "google.co.jp", false, kGooglePins, "", DOMAIN_CO_JP },
  {12, true, "google.co.ke", false, kGooglePins, "", DOMAIN_CO_KE },
  {12, true, "google.co.kr", false, kGooglePins, "", DOMAIN_CO_KR },
  {12, true, "google.co.ls", false, kGooglePins, "", DOMAIN_CO_LS },
  {12, true, "google.co.ma", false, kGooglePins, "", DOMAIN_CO_MA },
  {12, true, "google.co.mz", false, kGooglePins, "", DOMAIN_CO_MZ },
  {12, true, "google.co.nz", false, kGooglePins, "", DOMAIN_CO_NZ },
  {12, true, "google.co.th", false, kGooglePins, "", DOMAIN_CO_TH },
  {12, true, "google.co.tz", false, kGooglePins, "", DOMAIN_CO_TZ },
  {12, true, "google.co.ug", false, kGooglePins, "", DOMAIN_CO_UG },
  {12, true, "google.co.uk", false, kGooglePins, "", DOMAIN_CO_UK },
  {12, true, "google.co.uz", false, kGooglePins, "", DOMAIN_CO_UZ },
  {12, true, "google.co.ve", false, kGooglePins, "", DOMAIN_CO_VE },
  {12, true, "google.co.vi", false, kGooglePins, "", DOMAIN_CO_VI },
  {12, true, "google.co.za", false, kGooglePins, "", DOMAIN_CO_ZA },
  {12, true, "google.co.zm", false, kGooglePins, "", DOMAIN_CO_ZM },
  {12, true, "google.co.zw", false, kGooglePins, "", DOMAIN_CO_ZW },
  {13, true, "google.com.af", false, kGooglePins, "", DOMAIN_COM_AF },
  {13, true, "google.com.ag", false, kGooglePins, "", DOMAIN_COM_AG },
  {13, true, "google.com.ai", false, kGooglePins, "", DOMAIN_COM_AI },
  {13, true, "google.com.ar", false, kGooglePins, "", DOMAIN_COM_AR },
  {13, true, "google.com.au", false, kGooglePins, "", DOMAIN_COM_AU },
  {13, true, "google.com.bd", false, kGooglePins, "", DOMAIN_COM_BD },
  {13, true, "google.com.bh", false, kGooglePins, "", DOMAIN_COM_BH },
  {13, true, "google.com.bn", false, kGooglePins, "", DOMAIN_COM_BN },
  {13, true, "google.com.bo", false, kGooglePins, "", DOMAIN_COM_BO },
  {13, true, "google.com.br", false, kGooglePins, "", DOMAIN_COM_BR },
  {13, true, "google.com.by", false, kGooglePins, "", DOMAIN_COM_BY },
  {13, true, "google.com.bz", false, kGooglePins, "", DOMAIN_COM_BZ },
  {13, true, "google.com.cn", false, kGooglePins, "", DOMAIN_COM_CN },
  {13, true, "google.com.co", false, kGooglePins, "", DOMAIN_COM_CO },
  {13, true, "google.com.cu", false, kGooglePins, "", DOMAIN_COM_CU },
  {13, true, "google.com.cy", false, kGooglePins, "", DOMAIN_COM_CY },
  {13, true, "google.com.do", false, kGooglePins, "", DOMAIN_COM_DO },
  {13, true, "google.com.ec", false, kGooglePins, "", DOMAIN_COM_EC },
  {13, true, "google.com.eg", false, kGooglePins, "", DOMAIN_COM_EG },
  {13, true, "google.com.et", false, kGooglePins, "", DOMAIN_COM_ET },
  {13, true, "google.com.fj", false, kGooglePins, "", DOMAIN_COM_FJ },
  {13, true, "google.com.ge", false, kGooglePins, "", DOMAIN_COM_GE },
  {13, true, "google.com.gh", false, kGooglePins, "", DOMAIN_COM_GH },
  {13, true, "google.com.gi", false, kGooglePins, "", DOMAIN_COM_GI },
  {13, true, "google.com.gr", false, kGooglePins, "", DOMAIN_COM_GR },
  {13, true, "google.com.gt", false, kGooglePins, "", DOMAIN_COM_GT },
  {13, true, "google.com.hk", false, kGooglePins, "", DOMAIN_COM_HK },
  {13, true, "google.com.iq", false, kGooglePins, "", DOMAIN_COM_IQ },
  {13, true, "google.com.jm", false, kGooglePins, "", DOMAIN_COM_JM },
  {13, true, "google.com.jo", false, kGooglePins, "", DOMAIN_COM_JO },
  {13, true, "google.com.kh", false, kGooglePins, "", DOMAIN_COM_KH },
  {13, true, "google.com.kw", false, kGooglePins, "", DOMAIN_COM_KW },
  {13, true, "google.com.lb", false, kGooglePins, "", DOMAIN_COM_LB },
  {13, true, "google.com.ly", false, kGooglePins, "", DOMAIN_COM_LY },
  {13, true, "google.com.mt", false, kGooglePins, "", DOMAIN_COM_MT },
  {13, true, "google.com.mx", false, kGooglePins, "", DOMAIN_COM_MX },
  {13, true, "google.com.my", false, kGooglePins, "", DOMAIN_COM_MY },
  {13, true, "google.com.na", false, kGooglePins, "", DOMAIN_COM_NA },
  {13, true, "google.com.nf", false, kGooglePins, "", DOMAIN_COM_NF },
  {13, true, "google.com.ng", false, kGooglePins, "", DOMAIN_COM_NG },
  {13, true, "google.com.ni", false, kGooglePins, "", DOMAIN_COM_NI },
  {13, true, "google.com.np", false, kGooglePins, "", DOMAIN_COM_NP },
  {13, true, "google.com.nr", false, kGooglePins, "", DOMAIN_COM_NR },
  {13, true, "google.com.om", false, kGooglePins, "", DOMAIN_COM_OM },
  {13, true, "google.com.pa", false, kGooglePins, "", DOMAIN_COM_PA },
  {13, true, "google.com.pe", false, kGooglePins, "", DOMAIN_COM_PE },
  {13, true, "google.com.ph", false, kGooglePins, "", DOMAIN_COM_PH },
  {13, true, "google.com.pk", false, kGooglePins, "", DOMAIN_COM_PK },
  {13, true, "google.com.pl", false, kGooglePins, "", DOMAIN_COM_PL },
  {13, true, "google.com.pr", false, kGooglePins, "", DOMAIN_COM_PR },
  {13, true, "google.com.py", false, kGooglePins, "", DOMAIN_COM_PY },
  {13, true, "google.com.qa", false, kGooglePins, "", DOMAIN_COM_QA },
  {13, true, "google.com.ru", false, kGooglePins, "", DOMAIN_COM_RU },
  {13, true, "google.com.sa", false, kGooglePins, "", DOMAIN_COM_SA },
  {13, true, "google.com.sb", false, kGooglePins, "", DOMAIN_COM_SB },
  {13, true, "google.com.sg", false, kGooglePins, "", DOMAIN_COM_SG },
  {13, true, "google.com.sl", false, kGooglePins, "", DOMAIN_COM_SL },
  {13, true, "google.com.sv", false, kGooglePins, "", DOMAIN_COM_SV },
  {13, true, "google.com.tj", false, kGooglePins, "", DOMAIN_COM_TJ },
  {13, true, "google.com.tn", false, kGooglePins, "", DOMAIN_COM_TN },
  {13, true, "google.com.tr", false, kGooglePins, "", DOMAIN_COM_TR },
  {13, true, "google.com.tw", false, kGooglePins, "", DOMAIN_COM_TW },
  {13, true, "google.com.ua", false, kGooglePins, "", DOMAIN_COM_UA },
  {13, true, "google.com.uy", false, kGooglePins, "", DOMAIN_COM_UY },
  {13, true, "google.com.vc", false, kGooglePins, "", DOMAIN_COM_VC },
  {13, true, "google.com.ve", false, kGooglePins, "", DOMAIN_COM_VE },
  {13, true, "google.com.vn", false, kGooglePins, "", DOMAIN_COM_VN },
  {9, true, "google.cv", false, kGooglePins, "", DOMAIN_GOOGLE_CV },
  {9, true, "google.cz", false, kGooglePins, "", DOMAIN_GOOGLE_CZ },
  {9, true, "google.de", false, kGooglePins, "", DOMAIN_GOOGLE_DE },
  {9, true, "google.dj", false, kGooglePins, "", DOMAIN_GOOGLE_DJ },
  {9, true, "google.dk", false, kGooglePins, "", DOMAIN_GOOGLE_DK },
  {9, true, "google.dm", false, kGooglePins, "", DOMAIN_GOOGLE_DM },
  {9, true, "google.dz", false, kGooglePins, "", DOMAIN_GOOGLE_DZ },
  {9, true, "google.ee", false, kGooglePins, "", DOMAIN_GOOGLE_EE },
  {9, true, "google.es", false, kGooglePins, "", DOMAIN_GOOGLE_ES },
  {9, true, "google.fi", false, kGooglePins, "", DOMAIN_GOOGLE_FI },
  {9, true, "google.fm", false, kGooglePins, "", DOMAIN_GOOGLE_FM },
  {9, true, "google.fr", false, kGooglePins, "", DOMAIN_GOOGLE_FR },
  {9, true, "google.ga", false, kGooglePins, "", DOMAIN_GOOGLE_GA },
  {9, true, "google.ge", false, kGooglePins, "", DOMAIN_GOOGLE_GE },
  {9, true, "google.gg", false, kGooglePins, "", DOMAIN_GOOGLE_GG },
  {9, true, "google.gl", false, kGooglePins, "", DOMAIN_GOOGLE_GL },
  {9, true, "google.gm", false, kGooglePins, "", DOMAIN_GOOGLE_GM },
  {9, true, "google.gp", false, kGooglePins, "", DOMAIN_GOOGLE_GP },
  {9, true, "google.gr", false, kGooglePins, "", DOMAIN_GOOGLE_GR },
  {9, true, "google.gy", false, kGooglePins, "", DOMAIN_GOOGLE_GY },
  {9, true, "google.hk", false, kGooglePins, "", DOMAIN_GOOGLE_HK },
  {9, true, "google.hn", false, kGooglePins, "", DOMAIN_GOOGLE_HN },
  {9, true, "google.hr", false, kGooglePins, "", DOMAIN_GOOGLE_HR },
  {9, true, "google.ht", false, kGooglePins, "", DOMAIN_GOOGLE_HT },
  {9, true, "google.hu", false, kGooglePins, "", DOMAIN_GOOGLE_HU },
  {9, true, "google.ie", false, kGooglePins, "", DOMAIN_GOOGLE_IE },
  {9, true, "google.im", false, kGooglePins, "", DOMAIN_GOOGLE_IM },
  {11, true, "google.info", false, kGooglePins, "", DOMAIN_GOOGLE_INFO },
  {9, true, "google.iq", false, kGooglePins, "", DOMAIN_GOOGLE_IQ },
  {9, true, "google.is", false, kGooglePins, "", DOMAIN_GOOGLE_IS },
  {9, true, "google.it", false, kGooglePins, "", DOMAIN_GOOGLE_IT },
  {12, true, "google.it.ao", false, kGooglePins, "", DOMAIN_IT_AO },
  {9, true, "google.je", false, kGooglePins, "", DOMAIN_GOOGLE_JE },
  {9, true, "google.jo", false, kGooglePins, "", DOMAIN_GOOGLE_JO },
  {11, true, "google.jobs", false, kGooglePins, "", DOMAIN_GOOGLE_JOBS },
  {9, true, "google.jp", false, kGooglePins, "", DOMAIN_GOOGLE_JP },
  {9, true, "google.kg", false, kGooglePins, "", DOMAIN_GOOGLE_KG },
  {9, true, "google.ki", false, kGooglePins, "", DOMAIN_GOOGLE_KI },
  {9, true, "google.kz", false, kGooglePins, "", DOMAIN_GOOGLE_KZ },
  {9, true, "google.la", false, kGooglePins, "", DOMAIN_GOOGLE_LA },
  {9, true, "google.li", false, kGooglePins, "", DOMAIN_GOOGLE_LI },
  {9, true, "google.lk", false, kGooglePins, "", DOMAIN_GOOGLE_LK },
  {9, true, "google.lt", false, kGooglePins, "", DOMAIN_GOOGLE_LT },
  {9, true, "google.lu", false, kGooglePins, "", DOMAIN_GOOGLE_LU },
  {9, true, "google.lv", false, kGooglePins, "", DOMAIN_GOOGLE_LV },
  {9, true, "google.md", false, kGooglePins, "", DOMAIN_GOOGLE_MD },
  {9, true, "google.me", false, kGooglePins, "", DOMAIN_GOOGLE_ME },
  {9, true, "google.mg", false, kGooglePins, "", DOMAIN_GOOGLE_MG },
  {9, true, "google.mk", false, kGooglePins, "", DOMAIN_GOOGLE_MK },
  {9, true, "google.ml", false, kGooglePins, "", DOMAIN_GOOGLE_ML },
  {9, true, "google.mn", false, kGooglePins, "", DOMAIN_GOOGLE_MN },
  {9, true, "google.ms", false, kGooglePins, "", DOMAIN_GOOGLE_MS },
  {9, true, "google.mu", false, kGooglePins, "", DOMAIN_GOOGLE_MU },
  {9, true, "google.mv", false, kGooglePins, "", DOMAIN_GOOGLE_MV },
  {9, true, "google.mw", false, kGooglePins, "", DOMAIN_GOOGLE_MW },
  {9, true, "google.ne", false, kGooglePins, "", DOMAIN_GOOGLE_NE },
  {12, true, "google.ne.jp", false, kGooglePins, "", DOMAIN_NE_JP },
  {10, true, "google.net", false, kGooglePins, "", DOMAIN_GOOGLE_NET },
  {9, true, "google.nl", false, kGooglePins, "", DOMAIN_GOOGLE_NL },
  {9, true, "google.no", false, kGooglePins, "", DOMAIN_GOOGLE_NO },
  {9, true, "google.nr", false, kGooglePins, "", DOMAIN_GOOGLE_NR },
  {9, true, "google.nu", false, kGooglePins, "", DOMAIN_GOOGLE_NU },
  {13, true, "google.off.ai", false, kGooglePins, "", DOMAIN_OFF_AI },
  {9, true, "google.pk", false, kGooglePins, "", DOMAIN_GOOGLE_PK },
  {9, true, "google.pl", false, kGooglePins, "", DOMAIN_GOOGLE_PL },
  {9, true, "google.pn", false, kGooglePins, "", DOMAIN_GOOGLE_PN },
  {9, true, "google.ps", false, kGooglePins, "", DOMAIN_GOOGLE_PS },
  {9, true, "google.pt", false, kGooglePins, "", DOMAIN_GOOGLE_PT },
  {9, true, "google.ro", false, kGooglePins, "", DOMAIN_GOOGLE_RO },
  {9, true, "google.rs", false, kGooglePins, "", DOMAIN_GOOGLE_RS },
  {9, true, "google.ru", false, kGooglePins, "", DOMAIN_GOOGLE_RU },
  {9, true, "google.rw", false, kGooglePins, "", DOMAIN_GOOGLE_RW },
  {9, true, "google.sc", false, kGooglePins, "", DOMAIN_GOOGLE_SC },
  {9, true, "google.se", false, kGooglePins, "", DOMAIN_GOOGLE_SE },
  {9, true, "google.sh", false, kGooglePins, "", DOMAIN_GOOGLE_SH },
  {9, true, "google.si", false, kGooglePins, "", DOMAIN_GOOGLE_SI },
  {9, true, "google.sk", false, kGooglePins, "", DOMAIN_GOOGLE_SK },
  {9, true, "google.sm", false, kGooglePins, "", DOMAIN_GOOGLE_SM },
  {9, true, "google.sn", false, kGooglePins, "", DOMAIN_GOOGLE_SN },
  {9, true, "google.so", false, kGooglePins, "", DOMAIN_GOOGLE_SO },
  {9, true, "google.st", false, kGooglePins, "", DOMAIN_GOOGLE_ST },
  {9, true, "google.td", false, kGooglePins, "", DOMAIN_GOOGLE_TD },
  {9, true, "google.tg", false, kGooglePins, "", DOMAIN_GOOGLE_TG },
  {9, true, "google.tk", false, kGooglePins, "", DOMAIN_GOOGLE_TK },
  {9, true, "google.tl", false, kGooglePins, "", DOMAIN_GOOGLE_TL },
  {9, true, "google.tm", false, kGooglePins, "", DOMAIN_GOOGLE_TM },
  {9, true, "google.tn", false, kGooglePins, "", DOMAIN_GOOGLE_TN },
  {9, true, "google.to", false, kGooglePins, "", DOMAIN_GOOGLE_TO },
  {9, true, "google.tp", false, kGooglePins, "", DOMAIN_GOOGLE_TP },
  {9, true, "google.tt", false, kGooglePins, "", DOMAIN_GOOGLE_TT },
  {9, true, "google.us", false, kGooglePins, "", DOMAIN_GOOGLE_US },
  {9, true, "google.uz", false, kGooglePins, "", DOMAIN_GOOGLE_UZ },
  {9, true, "google.vg", false, kGooglePins, "", DOMAIN_GOOGLE_VG },
  {9, true, "google.vu", false, kGooglePins, "", DOMAIN_GOOGLE_VU },
  {9, true, "google.ws", false, kGooglePins, "", DOMAIN_GOOGLE_WS },
  {21, true, "learn.doubleclick.net", false, kNoPins, "", DOMAIN_NOT_PINNED },
  {14, false, "www.paypal.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {14, false, "www.elanex.biz", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {10, true, "jottit.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {17, true, "sunshinepress.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {19, false, "www.noisebridge.net", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {8, false, "neg9.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {10, true, "riseup.net", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {9, false, "factor.cc", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {20, false, "members.mayfirst.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {20, false, "support.mayfirst.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, false, "id.mayfirst.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {18, false, "lists.mayfirst.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {26, false, "aladdinschools.appspot.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {12, true, "ottospora.nl", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {23, false, "www.paycheckrecords.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {12, false, "lastpass.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {16, false, "www.lastpass.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {12, true, "keyerror.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {11, false, "entropia.de", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, false, "www.entropia.de", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {9, true, "romab.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {14, false, "logentries.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {18, false, "www.logentries.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {10, true, "stripe.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {25, true, "cloudsecurityalliance.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {13, true, "login.sapo.pt", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {17, true, "mattmccutchen.net", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {9, true, "betnet.fr", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {11, true, "uprotect.it", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {12, false, "squareup.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {7, true, "cert.se", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {9, true, "crypto.is", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {18, true, "simon.butcher.name", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {8, true, "linx.net", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {11, false, "dropcam.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, false, "www.dropcam.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {28, true, "ebanking.indovinabank.com.vn", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {11, false, "epoxate.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {14, false, "torproject.org", true, kTorPins, "", DOMAIN_TORPROJECT_ORG },
  {19, true, "blog.torproject.org", true, kTorPins, "", DOMAIN_TORPROJECT_ORG },
  {20, true, "check.torproject.org", true, kTorPins, "", DOMAIN_TORPROJECT_ORG },
  {18, true, "www.torproject.org", true, kTorPins, "", DOMAIN_TORPROJECT_ORG },
  {20, true, "www.moneybookers.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, false, "ledgerscope.net", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {19, false, "www.ledgerscope.net", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {8, false, "kyps.net", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {12, false, "www.kyps.net", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, true, "app.recurly.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, true, "api.recurly.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {11, false, "greplin.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, false, "www.greplin.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {25, true, "luneta.nearbuysystems.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {10, true, "ubertt.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {7, true, "pixi.me", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {12, true, "grepular.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {14, false, "mydigipass.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {18, false, "www.mydigipass.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {24, false, "developer.mydigipass.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {28, false, "www.developer.mydigipass.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {22, false, "sandbox.mydigipass.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {26, false, "www.sandbox.mydigipass.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {10, true, "crypto.cat", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {23, true, "bigshinylock.minazo.net", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {8, true, "crate.io", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {11, false, "twitter.com", false, kTwitterComPins, "", DOMAIN_TWITTER_COM },
  {15, true, "www.twitter.com", false, kTwitterComPins, "", DOMAIN_TWITTER_COM },
  {15, true, "api.twitter.com", false, kTwitterCDNPins, "", DOMAIN_TWITTER_COM },
  {17, true, "oauth.twitter.com", false, kTwitterComPins, "", DOMAIN_TWITTER_COM },
  {18, true, "mobile.twitter.com", false, kTwitterComPins, "", DOMAIN_TWITTER_COM },
  {15, true, "dev.twitter.com", false, kTwitterComPins, "", DOMAIN_TWITTER_COM },
  {20, true, "business.twitter.com", false, kTwitterComPins, "", DOMAIN_TWITTER_COM },
  {20, true, "platform.twitter.com", false, kTwitterCDNPins, "", DOMAIN_TWITTER_COM },
  {13, true, "si0.twimg.com", false, kTwitterCDNPins, "", DOMAIN_TWIMG_COM },
  {21, true, "twimg0-a.akamaihd.net", false, kTwitterCDNPins, "", DOMAIN_AKAMAIHD_NET },
  {20, true, "braintreegateway.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {21, false, "braintreepayments.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {25, false, "www.braintreepayments.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {22, false, "emailprivacytester.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {11, true, "tor2web.org", false, kTor2webPins, "", DOMAIN_TOR2WEB_ORG },
  {23, true, "business.medbank.com.mt", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {12, true, "arivo.com.br", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {19, true, "www.apollo-auto.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {13, true, "www.cueup.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {9, false, "jitsi.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {13, false, "www.jitsi.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {18, false, "download.jitsi.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {6, true, "sol.io", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {12, false, "irccloud.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {16, false, "www.irccloud.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {18, false, "alpha.irccloud.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {9, true, "passwd.io", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {13, true, "browserid.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {17, true, "login.persona.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {11, false, "neonisi.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, true, "www.neonisi.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {17, true, "shops.neonisi.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, true, "piratenlogin.de", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {13, true, "howrandom.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {11, false, "intercom.io", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, false, "api.intercom.io", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, false, "www.intercom.io", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {15, true, "fatzebra.com.au", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {16, true, "csawctf.poly.edu", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {16, false, "makeyourlaws.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {20, false, "www.makeyourlaws.org", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {14, true, "iop.intuit.com", true, kNoPins, "", DOMAIN_NOT_PINNED },
  {12, false, "test.tack.io", false, kNoPins, "j6det.kfbj5.oweph.mdyxi.wvbch", DOMAIN_TACK_IO },
};
static const size_t kNumPreloadedSTS = ARRAYSIZE_UNSAFE(kPreloadedSTS);

static const struct HSTSPreload kPreloadedSNISTS[] = {
  {9, false, "gmail.com", true, kGooglePins, "", DOMAIN_GMAIL_COM },
  {14, false, "googlemail.com", true, kGooglePins, "", DOMAIN_GOOGLEMAIL_COM },
  {13, false, "www.gmail.com", true, kGooglePins, "", DOMAIN_GMAIL_COM },
  {18, false, "www.googlemail.com", true, kGooglePins, "", DOMAIN_GOOGLEMAIL_COM },
  {20, true, "google-analytics.com", false, kGooglePins, "", DOMAIN_GOOGLE_ANALYTICS_COM },
  {16, true, "googlegroups.com", false, kGooglePins, "", DOMAIN_GOOGLEGROUPS_COM },
};
static const size_t kNumPreloadedSNISTS = ARRAYSIZE_UNSAFE(kPreloadedSNISTS);

#endif // NET_BASE_TRANSPORT_SECURITY_STATE_STATIC_H_
